---
device:
  type: tun
  name: vpncloud%d
  path: ~
  fix-rp-filter: false
ip: 10.0.0.100
advertise-addresses: []
ifup: ~
ifdown: ~
crypto:
  password: my_password
  private-key: ~
  public-key: ~
  trusted-keys: []
  algorithms: []
listen: "3210"
peers:
  - 203.0.113.1:3210
  - 192.0.2.1:3210
peer-timeout: 300
keepalive: ~
beacon:
  store: ~
  load: ~
  interval: 3600
  password: ~
mode: normal
switch-timeout: 300
claims: []
auto-claim: true
port-forwarding: true
pid-file: ~
stats-file: ~
statsd:
  server: ~
  prefix: ~
user: ~
group: ~
hook: ~
hooks: {}
